MaMpf-HD/mampf

- app/views/shared/_footer.html.erb
This fixes one of the issues described in #25.
I reworked the code for the footer, but the final result should look similar to the one that is used at the moment.
> Fixed permanent page offset

- docker/production/entrypoint-master.sh
Remove rsync call in master entrypoint, since docker automatically copies these files to the correct location now.
> Stop copying pubic files in production

- app/controllers/registrations_controller.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/lectures/show.html.erb
- app/views/profile/_account.html.erb
- app/views/profile/edit.html.erb
- app/views/users/_delete_account.html.erb
- app/views/users/delete_account.coffee
- app/views/users/teacher.html.erb
- config/locales/de.yml
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20201015154231_add_archived_to_user.rb
- db/schema.rb
This pull request implements the feature that lectures/media can remain in the database when their editor/teacher deletes her/his MaMpf account. The account gets destroyed, but these materials (and only these) will be transfered to a new user who gets an `archived` flag.
> Proper user deletion

- config/application.rb
- config/routes.rb
- docker/development/docker-compose.yml
- docker/production/docker.env
- docker/run_tests/docker-compose.yml
This PR introduces a separate email adress that exception notification. Also, requests of any kind for nonexistent paths will be redirected to an error page (until now,this was only so for GET requests).
> Separate email for exception notifications

- app/views/submissions/_card_main.html.erb
This PR adds a downward arrow to the badge for submissions and correction, so that the bevhaviour of these buttons seems more intuitive.
> add downward arrow to submission and correction badges

- config/initializers/shrine.rb
Bug fix
- Linter
Sometimes Shrine workers cannot clean directories.
No.
> Set clean to false in Shrine for cache.

- app/assets/javascripts/upload.coffee
- app/views/submissions/_form.html.erb
- config/locales/de.yml
- config/locales/en.yml
Bug fix
- Linter
It was not clear, when a file is replaced/uploaded.
A helper now  guides now users.
No
> Add One help text concerning Upload of submissions

- app/models/assignment.rb
- app/models/submission.rb
feature
- Linter
matlab files are not accepted as as file type for assignments
matlab files are accepted as as file type for assignments
> allow matlab .m files as file type for assignments

- app/models/assignment.rb
feature
- Linter
.mlx files are not accepted for assignments
.mlx files are accepted for assignments
> adds .mlx as another file type for assignments

- app/controllers/assignments_controller.rb
- app/controllers/quiz_certificates_controller.rb
- app/controllers/submissions_controller.rb
- app/controllers/tutorials_controller.rb
- app/views/quiz_certificates/_form.html.erb
- app/views/submissions/_form.html.erb
- app/views/tutorials/index.html.erb
- config/locales/en.yml
Bug fix (#135)
- Linter
The controllers associated to the following models do not set specific locales: `assignment, submission, tutorial, quiz_certificate`
So, although the localizations are present in `.yml` locale files, they are not displayed.
The correct locales are set in the controllers, so they are displayed in the views.
> Locales for submissions

- app/controllers/registrations_controller.rb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- docker/development/docker-compose.yml
Bug fix
- Linter
No limits
Limits the number of signups
Edit ENV, to set custom time frame and user limits.
> Registration limit via ENV (#144) (#149)

- app/controllers/tutorials_controller.rb
- app/models/lecture.rb
- app/models/user.rb
Feature
- Linter
Tutorials in a lecture and tutorials belonging to a tutor are sorted by id.
Tutorials in a lecture and tutorials belonging to a tutor are sorted by title.
> Order tutorials by title

- app/controllers/submissions_controller.rb
- app/views/submissions/create.coffee
- config/locales/de.yml
- config/locales/en.yml
Bug fix
- Linter
Adding of users is done after creation of submission, which can lead to submissions without users if multiple create requests were fired.This behaviour is an unintended consequence of [this](https://github.com/MaMpf-HD/mampf/commit/8556fdf4c912118a7dbf9d5657420eb569224e54) commit.
Users are added before the submission is created (and the bug that should be fixed by the commit that caused the current behaviour remains fixed).
* **Does this PR introduce a breaking change?** (What changes might …
> Fix submission without users bug

- app/views/quizzes/_disclaimer.html.erb
- app/views/quizzes/take.html.erb
- config/locales/de.yml
- config/locales/en.yml
Feature (requested by users)
- Linter
Quizzees that are associated to a course (not to a lecture) get a disclaimer that informs the students that the notation and material in these quizzes may differ slightly from the material they have had in their lecture.
> add disclaimers to quizzes at course level

- app/controllers/media_controller.rb
- app/models/lecture.rb
- app/models/medium.rb
- app/views/media/_basics.html.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20201114125010_add_boost_to_medium.rb
- db/schema.rb
Feature
- Linter
There is a new field "boost" for media, which is a `float`. The default value is `0`. Media associated to courses or lectures will be sorted by boost first, giving the user the opportunity to override the default order.
A db:migrate should be run.
> add boost field to media

- .rubocop.yml
- app/assets/javascripts/upload.coffee
- app/controllers/media_controller.rb
- app/uploaders/submission_uploader.rb
- app/uploaders/video_uploader.rb
- app/views/media/_upload_video.html.erb
- app/workers/metadata_extractor.rb
- config/initializers/shrine.rb
Bug fix attempt.
Upload of large files videos sometimes (#143). One reason maybe that metadata extractiontakes too long (especially when RAM is scarce) and causes a timeout.
This PR moves the extraction of video metadata to a sidekiq worker that is triggered only when the user saves the video.
> Extract metadata later

- docker/production/proxy_location_config.txt
This change increases the timeout on the nginx reverse proxy to handle slow workers during large file uploads.
> double nginx timeout for worker read/write operations

- app/models/ability.rb
- app/views/items/_items.html.erb
Bug fix
In the lesson view, users could download unpublished media.
Unpublished media cannot be downloaded in the lesson view. Furthermore, access rights for editors to the show action for arbitrary  media that are not related to the editor are not granted any longer.
see above.
> restrict access to media

- app/assets/javascripts/upload.coffee
- config/locales/de.yml
- docker/production/proxy_location_config.txt
Bug fix
#143 
Timeouts are different between client and server. This PR synchronizes this. Also, the server sided timeouts are raised to 240s. From my experiments, larger files take a long time to be parsed by Rack (this is what is causing the delay). In the current setup, rasing the timeouts seems to be the only option. The question is of course whether we want that - during the parsing of large files, CPU use is 100% for a long time, probably slowing down the rest of the application. 
EDIT: Parsing probably …
> Synchronize timeout settings

- app/models/submission.rb
Bug fix
File names in bulk download zip can become too large for Windows.
File names in bulk download zip cannot become too large for Windows.
> limit filename length in bulk download zip

- app/controllers/announcements_controller.rb
- app/controllers/main_controller.rb
- app/views/announcements/_form.html.erb
- app/views/announcements/_row.html.erb
- app/views/announcements/index.html.erb
- app/views/main/home.html.erb
- app/views/main/start.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20201121151659_add_on_main_page_to_announcement.rb
- db/schema.rb
Feature
As admin, you can create general announcements, bu there is no way to put them on the MaMpf homepage (which would be useful e.g. to announce server downtimes)
As admin you can set announcements on the homepage (this is done under /announcements) and remove them from the homepage.
Run db:migrate (the announcement table has a new boolean column …
> allow putting announcements on MaMpf home page

- app/assets/stylesheets/submissions.scss
- app/controllers/tutorials_controller.rb
- app/models/ability.rb
- app/models/tutorial.rb
- app/views/tutorials/index.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
Feature
A button has been added in the tutorial view for tutors that allows them to  download a .csv file with just one column that contains the names of all teams.
> add csv export for team names

- db/migrate/20201129133117_remove_integer_id_from_submission.rb
- db/schema.rb
bug fix (kind of)
The integer_id column in the submission model (which has been uuid based since some migration) prevents db:schema:load form working. 
The interger_id column has been removed. 
Run `db:migrate`.
> remove integer id from submission

- app/controllers/application_controller.rb
- app/models/course.rb
- app/models/course_user_join.rb
- app/models/user.rb
- db/migrate/20201213123754_drop_course_user_join_table.rb
- db/schema.rb
Removal of redundant stuff
The course_user_join model is removed from the codebases. It has been redundant for a while, but is has apparently been forgotten to remove it.
> remove redundant course_user_join_model

- app/assets/javascripts/main.coffee
- app/helpers/application_helper.rb
- app/views/main/start.html.erb
Feature
In the accordion on ther start page, the collapses are trigered by clicking on links in the headers.
In the accordion on ther start page, the collapses are trigered by clicking on the tab.
> Make tabs clickable instead of links on start page

- config/environments/production.rb
- docker/production/Dockerfile.proxy
- docker/production/proxy_server_config.txt
This commit disables the nginx access
logs, so only warnings remain.
Additionally the dallii store memcached
client is replaced by the rails version
that uses dallii in the background
anyway. This should remove the relevant
deprecation warnings during container
builds.
> nginx no access_log and :cache_memcached

- app/models/course.rb
- app/views/courses/_basics.html.erb
- app/views/courses/_inspection_details.html.erb
- config/locales/de.yml
- config/locales/en.yml
Bug fix
In #189 we removed the course/user join table. Unfortunately we overlooked to references to to course#users in the views.
Write a course#users method that takes into account all users who have subscribed to lectures in that course.
> Add substitute method for users in course

- docker/development/Dockerfile
- docker/production/Dockerfile
- docker/run_cypress_tests/Dockerfile
update the pdfcomprezzor build process to use the newest version of docker! 
Note that there currently is no test for the upload feature .. Testing has been done manually :blush:
> update the pdfcomprezzor to use docker 1.16

- app/models/medium_publisher.rb
Bug fix
If a publication was scheduled for a medium by someone who is not an editor a the medium itself (e.g. a teacher of the associated lecture who did not edit the medium himself), then the publication would not occur at the scheduled time.
All persons who can edit the medium (with inhericance) can properly schedule publication. 
> fix error related to who can schedule a publication

- app/views/layouts/_head.html.erb
- app/views/layouts/clicker.html.erb
- app/views/layouts/edit_clicker.html.erb
- app/views/layouts/geogebra.html.erb
This pull request updates katex to 0.13.9 to support CD-diagramms:
```
\begin{CD}
A @>f>> B \\
@VxVV @AAyA\\
C @>g>> D
\end{CD}
```
> Upgrade katex to 0.13.9

- app/controllers/media_controller.rb
- app/views/layouts/_head_additional_js.html.erb
- app/views/media/_statistics.html.erb
- app/views/media/get_statistics.coffee
Updates the chart.js dependency and creates plots for video access and downloads.
The statistics only show the total number of downloads/thyme play backs.
There is a nice plot.
no
> Playback statistics

- app/models/submission.rb
- app/views/tutorials/_bulk_correction_form.html.erb
Changed filetypes for bulkupload of corrections to allow all types. Tested on experimental.
(Small) Issue:
If you bulkupload zip files, the files in the zip get counted to the total, meaning number of successful correction uploads can exceed the number of submissions currently.
> allowed other filetypes for bulkupload

- app/assets/javascripts/upload.coffee
- app/models/submission.rb
- app/views/tutorials/_bulk_correction_form.html.erb
Fixes the behaviour described by the following comment:
"Ich habe gerade glaube ich einen Bug in dem Upload-js-Paket von Henrik Reinstädtler Henrik gefunden: Wenn man bei einem Medium bei einem Video statt eines .mp4 ein .pdf hochlädt, kriegt man korrekterweise angezeigt, dass es den falschen mime-typ hat. Wenn man direkt danach ein .mp4 hochlädt, sieht es so aus, als habe der Upload geklappt. Wenn man dann aber speichert, wird das Medium gar nicht gespeichert (es gibt einen Rollback). Offenbar wird in dem Formular was falsches übermittelt."
The issue was that uploading multiple files in a form that only supports one file still lead to a list being populated, out of which only the first element was …
> Fix upload bug

- docker/development/docker-compose.yml
- docker/production/docker-compose.production.yml
- docker/production/docker.env
Hey,
here are the changes to environment variables in production. I've also added an IMAP container to the development setup.
Note the additional variable IMAP_IGNORE_TLS_CERT=1 in development. The development server runs with TLS, but uses a self-signed certificate. You can setup your mail client as described [here](https://github.com/antespi/docker-imap-devel). Username is mampf@localhost, password: mampf. Take a look at the changes in docker-compose.yaml to find out what the actual values for the ports are.
The SMTP Server is separate from the one offered by mailcatcher and there currently is no environment variable indicating where to find it. (it listens on port 1025). Maybe if you want to add automated tests, you should add an other variable yourself.
In addition to all this I took …
> Imap server

- docker/production/Dockerfile.proxy
This is a minor bugfix. The nginx proxy complains, that a directory is missing during config generation. It needs to be created to fix the error.
> Resolve template error in nginx config generation

- app/workers/interaction_saver.rb
Policy change
referrer_url is ignored in interactions databse if it is an external referrer
referrer_url is ignored in interactions databse if it is an external referrer
> change saving policy for referrer url in interactions

- app/assets/javascripts/quizzes.coffee
Bug fix
When selecting a default target for a quiz vertex is canceled, nothing happens
When selecting a default target for a quiz vertex is canceled, the previous state is restored.
> correct typo that causes bug

- docker/nginx.tmpl
Add mime types to nginx config in order to get wasm working again.
This adds more than just the wasm type, as some other common types should be defined as well.
> wasm fix for nginx

- app/controllers/users_controller.rb
- app/models/user.rb
Bug fix
Speakers of talks who have added a medium are listed in the admin section as "Editors".
They are no longer listed in the admin section as "Editors".
> Remove talk speakers who have talk media from elevated users

- app/controllers/tutorials_controller.rb
- app/views/layouts/administration.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/application_no_sidebar.html.erb
- app/views/layouts/devise.html.erb
- app/views/tutorials/_bulk_correction_form.html.erb
- app/views/tutorials/bulk_upload.coffee
- config/locales/de.yml
- config/locales/en.yml
Tries to address the zero-byte upload error seen recently.
For some reason, the save button was at some point enabled to be clicked on before the files
were uploaded. This might have been the cause of the error for multiple people.
It has now been disabled again and, if the error persists, a message is displayed urging
to try again or contact us.
This PR also allows <br> tags inside flash alerts.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to …
> Fix zero byte uploads

- INSTALL.md
- docker/development/docker-compose.yml
**To be discussed:** Shoud the env vars `DB_SQL_PRESEED_URL` and `UPLOADS_PRESEED_URL` be present by default so that mampf automatically populates its database?
---
Bug fix
Currently the autosetup was broken due to out of date links.
The autosetup works again and the docs read a little nicer
Nope
> fix the autosetup

- docker/development/docker-compose.yml
- docker/production/docker-compose.production.yml
* **What kind of change does this PR introduce?**
Bug fix
* **What is the current behavior?**
Maybe its a docker upstream bug, but there really is no reason to use ssh references :)
```
$ docker compose -f docker-compose.production.yml build
[+] Building 0.0s (0/0)
[+] Building 0.1s (0/1)
[+] Building 5.0s (1/1) FINISHED
=> ERROR [internal] load git source git@github.com:MaMpf-HD/mampf.git#production 5.0s
------
[+] Building 5.0s (1/1) FINISHED
=> ERROR [internal] load git source git@github.com:MaMpf-HD/mampf.git#production 5.0s
------
> [internal] load git source git@github.com:MaMpf-HD/mampf.git#production:
------
failed to solve: Unimplemented: Unimplemented: unknown service moby.sshforward.v1.SSH
```
* **What is the new behavior …
> small docker fixes

- app/controllers/application_controller.rb
- app/controllers/registrations_controller.rb
Registration parameters are now sanitized in the way the devise documentation recommends it. Maybe this
fixes #436 (or at least stops the exceptions from happening in these cases). 
> Change the way registration params are sanitized

- app/views/users/_data.html.erb
This PR adds a missing case in an `if` statement in the user edit view and closes issue #448.
> fix missing media in user edit view

- app/views/layouts/application.html.erb
This PR renders the sidebar in searches only if the lecture variable is non-nil.
> hotfix: render sidebar only if lecture is present

- app/assets/stylesheets/sidebar.scss
Bug, closes #467 
See #467
List items are now shown correctly (again). The problem was that I didn't know our pipeline (with webpacker and the like) compiled all `.js` files together into one big bundle that gets applied to the whole page. Thus, I used `.li { ... }` as a selector in the sidebar `.css` file as of #446. The `display: flex` was therefore applied to every `li` item on the page, including the pane that showed up in a very weird way. Fixed this by restricting the CSS selector.
* **Does this PR …
> Fix card body flex css

- app/views/profile/_data.html.erb
- app/views/profile/edit.html.erb
- config/locales/de.yml
- config/locales/en.yml
Small redesign
During registrations, users are redirected to the profile view, so that they can finish their profile. In the bottom, of that page, the "request data" button might be mistaken for a kind-of "Finish registration" button.
The request data button is now left-aligned. Additionally, I've added a "Back to home" button below that.
> Avoid confusion with "Request data" button

- app/assets/stylesheets/media.scss
- app/controllers/media_controller.rb
- app/helpers/media_helper.rb
- app/views/media/_external_link.html.erb
- app/views/media/_external_link_card.html.erb
- app/views/media/medium/_buttons.html.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20230427124337_add_external_reference_link_description_to_medium.rb
- db/schema.rb
Closes #479
new feature, see #479 for more details
> Add display text for external medium links

- .rubocop.yml
- Gemfile
- Gemfile.lock
Update rubocop version for use with the [**Ruby LSP** VS Code extension](https://github.com/Shopify/vscode-ruby-lsp) (Language server that works hand in hand with a ruby formatter of your choice, in our case rubocop, and automatically detects rubocop settings).
> Update rubocop version

- app/assets/stylesheets/media.scss
- app/views/lectures/edit/_media.html.erb
- app/views/media/_table_column.html.erb
Closes #497 
While viewing the media of a course, links were randomly placed and invisible (e.g. on the route: `http://localhost:3000/courses/2/edit`). This was (mainly) due to a wrongly placed bootstrap class `tab-content` inside a column layout (wrapping only one column instead of the whole row).
> Fix ghost links in nested tabs

- Gemfile
- Gemfile.lock
- app/controllers/commontator/comments_controller.rb
- config/application.rb
In this PR we switch back to the current version of the commontator gem hosted on github, no longer using our own fork. This fixes #445.
> Use default version of commontator gem instead of own fork

- docker/development/Dockerfile
- docker/production/Dockerfile
- docker/run_cypress_tests/Dockerfile
- package.json
- yarn.lock
> Continuous Release 1.7.2 (Patch)

- app/assets/javascripts/lectures.coffee
This fixes #514. I added a missing event listener that for the cancel lecture comments button (it is done exactly the same way for the cancel buttons in the other accordion folds).
> add event listener for cancel lecture comments button

- app/assets/javascripts/datetimepicker.js
- app/assets/javascripts/media.coffee
- app/javascript/packs/application.js
- app/javascript/packs/application.sass
- app/views/assignments/_form.html.erb
- app/views/assignments/_row.html.erb
- app/views/assignments/create.coffee
- app/views/assignments/edit.coffee
- app/views/assignments/new.js.erb
- app/views/assignments/update.coffee
- app/views/layouts/_head.html.erb
- app/views/lectures/edit/_assignments.html.erb
- app/views/media/_publish_modal.html.erb
- config/locales/de.yml
- config/locales/en.yml
- package.json
- yarn.lock
The previously used JQuery datetimepicker was imported like this
```js
import css from 'jquery-datetimepicker/build/jquery.datetimepicker.min.css'
import myLib from 'imports-loader?imports=default%20jquery%20$!./../../../node_modules/jquery-datetimepicker/build/jquery.datetimepicker.full.min.js'
```
This dirty fix to direct webpack to the node modules folder has already caused too much pain since this was of course very fragile and thus failed often and seemingly in an undeterministic way. A quick fix was to change the import path, load the page again, then change the path back, so that webpack(er) picks up the changes. This has to find an end.
**Therefore, this PR replaces the previously used [JQuery datetimepicker](https://github.com/xdan/datetimepicker) with the [Tempus Dominus …
> Replace datetimepicker

- config/webpacker.yml
The application bundle was not correctly served in the local docker setup and instead a debug version was used and an error thrown in the browser console.
We fix this by specifying where webpacker should save the static files (default location where rails will pick it up in the "old" sprockets assets pipeline we use). Production and test environments are not affected by this as they precompile all the assets in advance and do not use the webpacker dev server to hot reload files during development.
See also [this medium post](https://medium.com/@rubalps/rails-cloudfront-webpack-823558c71b58) and [this comment](https://github.com/rails/webpacker/issues/1651#issuecomment-513482825) for the issue.
> Fix application bundle not being served by webpacker in dev-setup

- app/assets/javascripts/datetimepicker.js
- app/views/layouts/_head.html.erb
As of #526, the icons in the admin navbar did not work anymore as we have included FontAwesome6 for Tempus Dominus, however they seem to not be compliant with v5 we use so far. Hence, we remove v6 now and continue to rely on v5 and can then upgrade to v6 later by upgrading all icons in MaMpf to v6 (not just the datetimepicker icons).
> Stay with FontAwesome5 icons

- app/assets/stylesheets/application.scss
In the Apple Safari browser, the dot under the currently active navbar-item was not placed at the correct position. This is how it should be:
⚠ Before merging: let Apple user actually test this on mampf-experimental.
> Fix styling of small dot indicating current navbar item

- app/assets/stylesheets/admin.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/navbar.scss
- app/views/administration/_navbar.html.erb
- app/views/layouts/administration.html.erb
- app/views/shared/_navbar.html.erb
**I've redesigned the admin navbar to reflect the new look & feel introduced in #451**. I hope this new design is ok - even though of course every redesign might have its opponents ;)
With regards to the background: In my opinion, the old yellow background color conveys the impression of yellowed paper. It was originally introduced to make clear to teachers, editors etc. that they are in a mode where one has to pay more attention as one can add/edit/delete things. I hope this is also clear with the new design: instead of a blue navbar, it is red/purple-ish and the background is covered with a grey dot pattern inspired by the [Photoshop Beta](https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/06/photoshop-beta-app-logo.jpg) logo (however they use lines instead of dots). …
> Redesign admin navbar & background

- Gemfile.lock
- app/views/layouts/devise_mailer.html.erb
- app/views/layouts/mailer.html.erb
**Update `bootstrap` version from `5.2.1` to `5.3.1`**, so that #527 works correctly (`z-index` did not work properly, see comment [over there](https://github.com/MaMpf-HD/mampf/pull/527#issuecomment-1694698091)).
Command used:
```
bundle update bootstrap
```
Note that `bundle update bootstrap --conservative` did not work (containers did not start due to dependency errors).
See migration guide [here](https://getbootstrap.com/docs/5.3/migration/) for what has changed in Bootstrap.
> Upgrade bootstrap to v5.3.1

- app/views/tutorials/_bulk_correction_form.html.erb
- config/locales/de.yml
- config/locales/en.yml
This fixes #557 by aiming for a better wording and replacing "file" by "files" to make clear that multiple files can be selected.
> Improve bulk upload description

- app/models/user.rb
- db/migrate/20231101100015_add_devise_trackable_columns_to_users.rb
- db/schema.rb
In preparation of a later PR that will allow us to remove users that have not logged in for a very long time (see #532), we add tracking of the last sign in date. This is done via Devise's `:trackable` module. By default, this also stores IP adresses, which we do not want for GDPR reasons, so we make sure that the default is overridden and no IP data are stored.
> Track last sign in date

- .rubocop.yml
- Gemfile
- Gemfile.lock
Related:
- #560
- #562 
**See the new [`.rubocop.yml`](https://github.com/MaMpf-HD/mampf/blob/feature/redo-rubocop-config/.rubocop.yml) from this PR.**
[Automatically Generated Configuration](https://docs.rubocop.org/rubocop/configuration.html#automatically-generated-configuration). And some useful commands.
```
bundle exec rubocop --autocorrect (maybe also use option: --disable-uncorrectable)
rubocop --auto-gen-config --no-exclude-limit
[work through .rubocop_todo.yml]
rubocop --regenerate-todo
```
---
Some stats using the new config at commit e768bfc:
```sh
$ bundle install
$ bundle exec rubocop --autocorrect 
704 files inspected, 7952 offenses detected, 6814 offenses corrected, 721 more offenses can be corrected with `rubocop -A`
$ bundle exec rubocop -A
704 files inspected, 1350 …
```
> Redo the Rubocop config

- config/webpack/environment.js
- docker/development/Dockerfile
- docker/production/Dockerfile
- docker/run_cypress_tests/Dockerfile
Upgrade Node.js to v20.10.0 (LTS until April 2026).
~~I tested this on the `experimental` branch and the run was successful (see Dozzle). Also check out [mampf-experimental](https://mampf-experimental.mathi.uni-heidelberg.de/).~~ Nope, that's what I hoped, but of course the old error keeps hunting us.
And we are not alone, the question for this error was viewed 2.5million times on Stack overflow [here](https://stackoverflow.com/q/69692842/9655481)! I will fix this! [maybe useful](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported#comment131441027_73465262)
In 8f67ce9, I finally fixed this issue after several failed attempts. See the comment in the code for further details. The `experimental` branch currently also points to this …
> Upgrade Node.js to v20 (LTS)

- app/controllers/media_controller.rb
Fixes #583.
This was due to the unsafe RuboCop rule in #566: [`Style/ArrayIntersect`](https://docs.rubocop.org/rubocop/cops_style.html#stylearrayintersect).
> Safety: This cop cannot guarantee that array1 and array2 are actually arrays while method intersect? is for arrays only.
That was the case here.
> Fix missing `to_a` to convert to Rails array

- .vscode/settings.json
Also see the 50/72 rule by [tpope](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
> Warn about too long GitHub commit messages

- db/migrate/20240116180000_fix_unread_comments_inconsistencies.rb
After merging #587, I found we don't see the "Fixed ..." lines in the log. That's because `config/environments/production.rb` sets the log level to `warn` which is above `debug` (and also above `info`). That's why I now use `warn` for the migration. Happy to hear if there are better solutions than this, but this should work ;)
> Use `warn` log level instead of `debug` for unread comments migration

- db/migrate/20240116180000_fix_unread_comments_inconsistencies.rb
- db/migrate/20240215100000_fix_unread_comments_inconsistencies_again.rb
- db/schema.rb
Fixes a bug in the migration of #587. See the explanation [in this file](https://github.com/MaMpf-HD/mampf/pull/594/files#diff-fa284461015009e7c99f1772cd453466a7129fab554aa18e3904cf6d263252d3R13-R43).
> Fix `unread_comments` migration

- app/assets/javascripts/application.js
- app/assets/javascripts/search_tags.js
- app/controllers/media_controller.rb
- app/models/medium.rb
- app/views/main/start/_media_search.html.erb
- app/views/media/catalog/_search_form.html.erb
- db/migrate/20240116180000_fix_unread_comments_inconsistencies.rb
- db/migrate/20240215100000_fix_unread_comments_inconsistencies_again.rb
- db/schema.rb
> Continuous Release v1.9.3

- eslint.config.mjs
- yarn.lock
See the related discussion [here](https://github.com/eslint/eslint/discussions/18114) for why we introduce this change. We need this for the file `edit.js.erb` in the annotation tool (`app/views/annotations/edit.js.erb`) for the line:
```js
var posted = <%= @posted %>;
```
As described in the discussion, this line is buggy for the autocorrection and emits the unnecessary "Unused eslint-disable directive" warning.
> Don't report unused disable directive (ESLint)

- app/controllers/clickers_controller.rb
- app/controllers/erdbeere_controller.rb
- app/controllers/lectures_controller.rb
- app/controllers/registrations_controller.rb
- app/helpers/application_helper.rb
- app/mailers/exception_handler/exception_mailer.rb
- app/models/user_cleaner.rb
- app/views/devise/registrations/new.html.erb
- app/views/exception_handler/mailers/new_exception.html.erb
- app/workers/interaction_saver.rb
- config/application.rb
- config/environments/production.rb
- config/initializers/default_setting.rb
- config/initializers/devise.rb
- config/initializers/thredded.rb
- docker/production/Dockerfile
- docker/production/docker.env
- lib/tasks/db.rake
Fixes #542.
Replace `ENV.fetch(..., nil)` by `ENV.fetch(...)` and `ENV[...]` by `ENV.fetch(...)` (whenever applicable). Also see this [SO answer](https://stackoverflow.com/a/47985757) for what the difference is.
Also synced the dummy `docker.env` file with the one used in production (added missing variables).
-  [x] Test [this comment](https://github.com/docker/compose/issues/5600#issuecomment-727905877) for experimental -> `source docker.env` on separate line not working, will try to source on same line...
-  ~~[ ] Reflect [this comment](https://github.com/docker/compose/issues/5600#issuecomment-727905877) in redeploy script on every stage (experimental/dev/main)~~
> [!tip]
> I've written a [**Stack Overflow question**](https://stackoverflow.com/questions/78098380/make-docker-env-variable …
> Raise key error if env variable is `nil` & update `docker.env`

- app/views/administration/_navbar.html.erb
A user complained that the binocular was not identifiable as a "search function" at first glance. This is why we are replacing it by a magnifier icon in this PR.
> Replace admin search icon

- .vscode/settings.json
In a new version of VSCode, the API was changed. We now use a boolean flag instead of a string.
> Fix `git.inputValidation` VSCode setting

- .vscode/settings.json
- app/models/medium.rb
- app/views/annotations/_form_content_further_help.html.erb
- app/views/media/play.html.erb
> Continuous Release 1.11.1

- .vscode/settings.json
- app/controllers/courses_controller.rb
- app/views/courses/_basics.html.erb
- config/locales/de.yml
- config/locales/en.yml
Only admins can update the editors of a course, the course editors themselves can't do this. Until now, this was a little inconsequentially only realized in the view by leaving out the corresponding form. This PR whitelists the `editor_ids` parameter only for admins and adds a helpdesk.
> Only allow admins to change course editors

- docker/development/docker-compose.yml
Previously, files to initialize an empty database with some development data was stored on a cloud storage associated to a university. We now have a custom repo for that: https://github.com/MaMpf-HD/mampf-init-data
This PR updates the links accordingly.
Tested locally with Docker and it works.
> Use new preseed links to init data in local db

- docker/development/docker-compose.yml
These env variables were accidentally included without a comment in #612. Here we comment them out again such that initializing the database with sample data is an active choice locally.
> Uncomment preseed Docker env vars

- db/schema.rb
This change was performed automatically by Rails locally.
> Add `public` prefix for `gen_random_uuid()` in db schema

- .vscode/settings.json
This change was performed automatically by VSCode due to https://github.com/Shopify/ruby-lsp/pull/1831
> Use new identifier for Ruby LSP VSCode plugin settings

- config/application.rb
Since it caused some trouble in production, we set the `raise_on_missing_translations flag` to false. We will have to look at what went wrong in more detail and fix the underlying issues before setting the flag back to `true`.
> Set raise_on_missing_translations flag to false

- Gemfile
- Gemfile.lock
Due to some change in policy regarding how rack parses requests from version 3 on, some of our nested forms are parsed in way that produces an incorrect parameters hash in the controller. In this hotfix we downgrade to Rack 2.2.9. We have to go through each form, update them and migrate to Rack 3 at a later time.
> Downgrade Rack to 2.2.9

- app/controllers/interactions_controller.rb
When clicking the `Export statistics` button in the admin view (corresponding to the `/interactions` route), we got an error. In this PR we fix the broken interactions controller by adding the missing `current_ability` method.
> Fix broken interactions controller

- db/interactions_schema.rb
- db/schema.rb
After a complete wipe and recreation of my Docker setup, Rails automatically updated the schema version to `7.1`. I forgot to do this in #554.
> Update active record schema version to 7.1

- Gemfile.lock
- yarn.lock
Dependencies were upgraded via `bundle update` and `yarn upgrade`.
Only lockfiles are affected as we didn't bump any major version. Note that while some security issues should be mitigated by this, we couldn't address many of those in the security tab. This is because webpacker has not updated its JS dependencies for a year and won't do so in the future as it is no longer actively developed. We should move away from webpacker (e.g. from webpack**er** to webpack) in the near future and address #454.
> Upgrade Gemfile and yarn dependencies

- Gemfile
- Gemfile.lock
In #609, we had to use an older version of `html-parser` (see commit 456ed14) for the forum engine `thredded` to still work with Rails 7.1. This was necessary due to https://github.com/thredded/thredded/issues/979. In the meantime, glebm made a commit on `thredded` to deal with this internally in their project, so we don't need to include the dependency `html-parser` on our side (see https://github.com/thredded/thredded/pull/981). Therefore, we get rid of `html-parser` and use the new commit from their GitHub repo directly.
- Run `bundle install` locally.
- Additionally, you will have to run `docker compose build mampf webpacker`, otherwise bundler is complaining in the Docker images.<br>If you happen to know a way to avoid rebuilding the whole image if we just update some gems let me …
> Pin `thredded` to recent Git commit

- docker/development/docker-compose.yml
- docker/production/docker-compose.production.yml
- docker/test/docker-compose.local.yml
- docker/test/docker-compose.yml
See [this](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements) for why we don't need it anymore:
> The top-level version property is defined by the Compose Specification for backward compatibility. It is only informative you'll receive a warning message that it is obsolete if used.
> Remove obsolete docker compose version specifiers

- app/assets/javascripts/thyme/chapter_manager.js
- app/assets/javascripts/thyme/metadata_manager.js
- app/assets/javascripts/thyme/thyme_player.js
This fixes #638.
In the code, probably due to historic reasons, references are referred to by "metadata" while chapters are called under the name "chapters".
Note that the interactive area might be opened even though no element is shown. This is by design: references can pop up at a later point in time in the video. If any reference is present (no matter the timestamp), the interactive area will already be opened for users to take note that a reference just appeared.
> Open interactive area if chapters or references are present in video

- app/models/medium.rb
This fixes #639 by removing the redundant `after_destroy` callback in the `Medium` model.
> Fix broken deletion of questions

- docker/test/Dockerfile
- docker/test/docker-compose.yml
This is to ensure that local changes in the `app` folder are reflected in the Docker container such that newly written tests can be run through without having to rebuild the whole Docker image.
- While the whole `app` folder is mounted to `/usr/src/app/app`, wee construct a specific `public` volume such that the `rake assets:precompile` task can populate the folder `usr/src/app/public/packs-test/`.
- Note that all files are still copied in the `Dockerfile` such that `rails assets:precompile` can work correctly. The `app/` folder is then later mounted "on top" of that.
- Also moved the entrypoint declaration to the place where it's declared in the development setup, just to achieve symmetry.
Please delete your old mampf test image (if you have one locally) before testing the changes made …
> Don't just mount `spec` folder, but complete `app` folder for tests

- spec/models/watchlist_entry_spec.rb
- spec/models/watchlist_spec.rb
Watchlist tests relied on strings coming from Rails. Instead, we now just check if errors are present and if they contain the respective keys.
(I noticed that these tests are flaky in #647).
> Fix flaky watchlist tests

- .vscode/settings.json
- Don't use ESLint experimental flag anymore (it's now in the official plugin version)
- Add the `.docker` folder to hidden folders
- Remove custom Ruby LSP command. This was an attempt to mitigate https://github.com/Shopify/ruby-lsp-rails/issues/382, however it did not work (or rather was too much effort), so we just don't use the few Ruby LSP server-dependent features (for that we would have to run it inside docker containers) and stick with the static code analysis with is sufficient for us.
> Don't use VSCode ESLint experimental flag anymore

- .config/commands/docker.justfile
- initialize.sh
This fixes DB preseeding that was introduced wrongly in #652.
For development, instead of seeding, we restore a sample database and then still use migrations.
For testing, we continue to use db seeding.
The respective Just command was adjusted to allow for reseeding without having to manually stop the mampf service beforehand. This will now be done automatically.
We also moved the SOLR indexing step to the end to avoid errors when SOLR is accessing the database while it is reseeded in the background.
Previously, the `db:create` command as issued twice, I've reduced it such that it only occurs once at the very beginning.
> Fix DB preseeding

- app/controllers/cypress/factories_controller.rb
- docker/test/docker-compose.yml
- spec/cypress/support/factorybot.js
In this PR we
- add an endpoint to skip the validation in the FactoryBot `create()` method. The function can be called from Cypress tests via `FactoryBot.createNoValidate(...)`
- expose Docker to another port (externally) to be able to start Cypress while the dev environment is running. The internal Docker port stays `3000`.
> Add endpoint to skip validation in Cypress tests

- spec/support/database_cleaner.rb
In #647, we noticed that our unit tests were failing in the pipeline (GitHub Actions). We noticed locally that the database is not fully cleaned and there are users left between tests. We now use the slower `deletion` strategy which will entirely delete the tables since transactions was not working for us. This might be due to `after_commit`or `after_save` callbacks as discussed [here](https://devopsvoyage.com/2018/09/26/get-most-of-the-database-cleaner.html).
Note that for the deletion strategy, we also tried out to set `pre_count` and `reset_ids` to `true` as described [here](https://github.com/DatabaseCleaner/database_cleaner-active_record?tab=readme-ov-file#strategy-configuration-options), but this made the tests slower, so we will omit those options.
For a discussion on delete vs. …
> Tests: Fix database cleaner separation

- .config/commands/docker.justfile
We add the two `just` commands
```
just docker up-logs
just docker logs
```
`just docker up-logs` allows you to start the containers in detached mode while still seeing the logs afterwards. Therefore, you can `Ctrl + C` out of your terminal afterwards and the containers will continue to run. `just docker logs` is used to attach back to the logs for a running container (by default the mampf container).
> Add `just` commands for docker logs

- spec/cypress/e2e/annotations_overview_spec.cy.js
- spec/cypress/e2e/lectures_spec.cy.js
- spec/factories/lectures.rb
Thanks to @fosterfarrell9 for pointing out that the trait `with_teacher_by_id` is actually not needed in FactoryBot. I removed it in this PR.
> Remove unnecessary `with_teacher_by_id` trait

- spec/models/course_spec.rb
As we are comparing to an array of values that contain German words like "Satz" or "Bsp.", we explicitly set the language to German here to avoid flaky tests in our pipeline due to the language of the user being chosen randomly.
This was originally discovered in [this GitHub Actions run](https://github.com/MaMpf-HD/mampf/actions/runs/10760063671/job/29837752555?pr=670).
> Explicitly set locale to German in course specs

- app/models/user.rb
- app/models/user_cleaner.rb
- spec/factories/users.rb
- spec/models/user_cleaner_spec.rb
In #647, we introduced the "UserCleaner" that deletes users that haven't logged in for too long. We now noticed that we don't deal with specific **edge cases related to user registration**. This means that our initial `where` clause
```ruby
User.where(last_sign_in_at: ...INACTIVE_USER_THRESHOLD.ago)
.or(User.where(last_sign_in_at: nil))
```
(to determine which users are inactive) is not sufficient to handle all cases. The new special cases are described as docstrings in the `app/models/user_cleaner.rb`.
Furthermore, we also replace `last_sign_in_at` by `current_sign_in_at` in this PR. See [this Devise code](https://github.com/heartcombo/devise/blob/72884642f5700439cc96ac560ee19a44af5a2d45/lib/devise/models/trackable.rb#L20-L23) to see the difference. `current_sign_in_at` always holds the …
> Deal with registration edge cases in UserCleaner

- app/controllers/annotations_controller.rb
- app/views/annotations/_annotation_area.html.erb
- app/views/lectures/edit/_comments.html.erb
- app/views/lectures/edit/_form.html.erb
- app/views/media/feedback.html.erb
- spec/cypress/e2e/annotations_spec.cy.js
In #668, we added an overview page for annotations (`/annotations`). In the following scenario, the behavior was incoherent:
- Teacher enables "allow students to share annotations with the teacher" in the lecture settings
- Student creates an annotation and shares it with the teacher
- Teacher disables "allow students to share annotations with the teacher" in the lecture settings
In the annotation overview page, the annotation was then listed under the section for students annotations. However, if the teacher clicked on it, they were redirected to the feedback player but didn't see the annotation.
We came to the conclusion that **we want the annotation to still be visible to the teacher in this case**. This is justified since the student has deliberately clicked on "Make the annotation …
> Fix annotation feedback not shown when share feature is disabled

- spec/rails_helper.rb
Linting failed due to [Rails/RootPathnameMethods](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsrootpathnamemethods), this PR fixes it.
> Safety: This cop is unsafe for autocorrection because Dir's children, each_child, entries, and glob methods return string element, but these methods of Pathname return Pathname element.
Apparently, `require` probably also works on `Pathname`. At least, the tests still work for me locally. I haven't checked the API for `require` though. This file is only used for tests anyways and as they still work I think it's not a big deal.
> Apply RootPathnameMethods linting suggestion

- .config/commands/utils.justfile
- .justfile
- docker/development/Dockerfile
Entity-relationship diagrams (ERD) have long been a very powerful tool for gaining insights and an overview of how the tables in a database are structured and associated to each other.
[`Rails ERD`](https://voormedia.github.io/rails-erd/) generates such diagrams based on runtime-informations using reflection (instead of static analysis). We have already specified this dependency in our Gemfile, but not used it so far.
> [!tip]
> In order to generate the PDF files locally, see the new Wiki entry [here](https://github.com/MaMpf-HD/mampf/wiki/Database#entity-relationship-diagrams-erd).
- Merge the voucher PR #671 into this branch locally to be able to create the voucher-related ERDs. Otherwise you will encounter errors like `raise NameError.new(message, name)`.
- Please make sure to rebuild …
> Init support for entity-relationship diagram creation (Ruby ERD)

- .vscode/extensions.json
We forgot to add the [Ruby Test explorer extension](https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter) that we're already using to the recommended VSCode extension. Added it now.
> Add Ruby Test explorer to recommended VSCode extensions

- app/workers/user_cleaner_job.rb
In production we encountered some failing UserCleanerJobs that were then repeatedly retried according to Sidekiq's error handling schedule, which result in some users getting several emails in a short period of time. As it is currently unclear why these jobs fail, this hotfix configures the UserCleanerJob in a way that failing jobs will not be retried.
> Hotfix: Set retry option to false for UserCleanerJob

- .config/commands/deps.justfile
- .justfile
We introduce new `just` commands to ease updating of dependencies, which we want to do regularly with every release.
> Init dependencies (deps) Just commands

- app/models/user.rb
- app/models/user_cleaner.rb
- spec/factories/users.rb
- spec/models/user_cleaner_spec.rb
**We already merged #693 in `dev`, but not in `main`. Due to the situation described in [Release `1.14.2`](https://github.com/MaMpf-HD/mampf/releases/tag/v1.14.2), we should get this one into production as quickly as possible.** 
Therefore, I've cherrypicked the merge commit to this new branch that we can directly merge into `main`.
---
* Deal with registration edge cases in UserCleaner
* Replace `last_sign_in_at` by `current_sign_in_at`
* Simplify inactive_users method via usage of scopes
* Add another scope for recently active users
> Deal with registration edge cases in UserCleaner (cherry-pick #693)

- app/views/media/_basics.html.erb
Fixes #704.
> Currently, if I create a new medium in a lecture where the lecture has "share annotations with teacher" set as true, the default for the new medium is that annotations are not shared. This is contrary to the intended behaviour.
In reality, the default was indeed that the status is inherited from the lecture. You could even open a video and verify that users can create annotations and share them with the teacher.
The problem was that originally, Marlon used the values `-1, 0, 1` to signify:
- `-1`: deactivated
- `0`: inherit
- `1`: activated
and I changed that to the following when I worked on the annotation tool:
- `-1`: inherit
- `0`: deactivated
- `1`: activated
However, I forgot to update the values at this place in the UI and therefore the wrong radio button was …
> Fix annotation status default value in UI

- spec/cypress/e2e/vouchers_redemptions_spec_helpers.js
The Cypress docs on [Actionability](https://docs.cypress.io/app/core-concepts/interacting-with-elements#Actionability) state that `.click()` will wait until the element reaches an "actionable state". This includes a check that the element is not hidden. However, in our tests we see that after visiting a page, a button is deemed "visible" even though it's not visible in the viewport yet.
Here we fix this flaky test. If this kind of behavior occurs more offen, either we use Cypress in a wrong manner or Cypress has a bug. In both cases it might be worth to consider overriding the `.click()` event by a custom method that calls `.should("be.visible").click()` instead, but this is something for a future PR (maybe).
> Fix flaky user deletion & redemption cypress test

- app/models/lesson.rb
See it [in the Rubocop docs](https://docs.rubocop.org/rubocop/cops_style.html#stylearrayintersect):
> This cop cannot guarantee that array1 and array2 are actually arrays while method intersect? is for arrays only.
Here, we deal with ActiveRecord objects that are not arrays, so we shouldn't use this. That's why I disable the lint here.
> Disable Style/ArrayIntersect on one line

- spec/cypress/e2e/profile_spec.cy.js
In #945, one Cypress test was failing (but only once). I couldn't reproduce the issue locally. With this PR, we intercept the submissions POST request and wait for it to be finished before logging the user out. This should hopefully prevent the flakiness in the future.
> Fix flaky Cypress submission test

- .config/commands/docker.justfile
In #719, I accidentally broke the `just` scripts because I forgot a `:`.
I won't run through the tests here since we only change a `.justfile`.
> Fix failing `just docker rebuild` script

- spec/cypress/e2e/vouchers_redemptions_spec.cy.js
- spec/cypress/e2e/vouchers_redemptions_spec_helpers.js
I was able to reproduce a flaky Cypress test locally. Fixed by adding `cy.then(() => {...});` statements after logging out, then logging in again as a new user. I also intercept a POST request now to make sure the deletion of the account is finished before we continue.
> Fix flaky voucher redemption Cypress test

- app/models/user.rb
In our `User` model, we have the following `searchable` related to Solr searches:
```ruby
searchable do
text :tutorial_name
end
```
There is however no longer any Solr based search for users (and has not been for a long time). The search field was introduced in [this commit](https://github.com/MaMpf-HD/mampf/commit/a76b0bf1695560e9b345994ea7d379967618a032), and [at a later time](https://github.com/MaMpf-HD/mampf/commit/b86f203aa17ea78facbfff24488089dbb2c9faed) the search field was changed to `tutorial_name`. However, this was only used in the [users controller](https://github.com/MaMpf-HD/mampf/commit/a76b0bf1695560e9b345994ea7d379967618a032#diff-cfdccd0a9d5df5a43aaad2a35d36ebbe187c52ad5fdc9846fa189d04537adb6e) in a `list` method which no longer exists. All user based searches have long …
> Remove obsolete tutorial name search field

- .vscode/settings.json
- app/mailers/user_cleaner_mailer.rb
- app/models/user_cleaner.rb
- app/views/user_cleaner_mailer/destroy_failed_email.text.erb
- spec/models/user_cleaner_spec.rb
In production, we got some weird errors, where the same users would get the user cleaner deletion mail (40 days) every day. This blog post summarizes well what I did wrong in the user cleaner: [Misuse of update/update! in Ruby on Rails](https://marcgg.com/blog/2020/04/08/rails-update-bang/).
The problem is a seemingly harmless statement:
https://github.com/MaMpf-HD/mampf/blob/412c981ed9058e82b7023c0552674c00acbe71bd/app/models/user_cleaner.rb#L77
But what if the `user` is invalid? Well, then `update` silently fails here. Instead, we want to set the deletion date in any case, so we should rather do
```rb
user.deletion_date = Date.current + 40.days
user.save(validate: false)
```
> [!tip]
> See also this PDF I've created to summarize the bug: [UserCleaner Update …
> Fix user cleaner for invalid users

- app/views/courses/_basics.html.erb
- app/views/lectures/_new.html.erb
- app/views/lectures/create.coffee
- app/views/lectures/new.coffee
- spec/cypress/e2e/lecture/new_lecture_specs.cy.js
- spec/cypress/support/commands.js
- spec/factories/courses.rb
This fixes #739. Turns out it was just a conditional that was forgotten in the restructuring of access rights in #671: Since there does no longer appear a form where you can select the teacher (unless you are admin), the javascript produced by `lectures/new.coffee` crashes. This has no consequence on `/administration` (where the exception also occurs), but on `courses/:id/edit` this prevents the modal from popping up.
I guess, some cypress tests should still be written for that.
UPDATE: After I had introduced the missing conditional in [this commit](https://github.com/MaMpf-HD/mampf/pull/752/commits/4f109ab510d61db5b436e369bcbff5d7b47929be) I decided it might be better just to let the backend do the job, so i just removed the corresponding js.
> Fix lecture creation

- app/models/notification.rb
This bug appears in production and can be reproduced locally as follows:
- Log in as teacher and create a voucher, e.g. for tutorials in Linear Algebra.
- Log in as student3 and redeem the voucher.
- Log in as teacher and try to update anything on your profile page, e.g. the language.
After this fix, this should not yield any error anymore. Please make sure you can reproduce the error beforehand to make sure that this is really a fix.
> Fix undefined method `lecture` for redemption

- Gemfile
- spec/models/medium_publisher_spec.rb
Some tests were suddenly failing. The reason is that hardcoded date strings were used and that `Assignment` validates them [here](https://github.com/MaMpf-HD/mampf/blob/a618d8b945040df3fd06c717e3a2655bffae0b6f/app/models/assignment.rb#L15-L22). What we should take away from this: don't use hard-coded date strings in the code. Tests should always work, no matter the point in time when they are launched.
> Fix failing test due to outdated, hardcoded date strings

- app/controllers/commontator/comments_controller.rb
- app/helpers/media_helper.rb
- app/views/commontator/comments/_body.html.erb
Comments, which resulted from creating a new annotation on a video and posting it as comment, were not editable anymore
```
NoMethodError (undefined method `video_link_timed' for an instance of #<Class:...>)
```
The reason is the call to `video_linked_timed` in `app/views/commontator/comments/_body.html.erb`. When this is rendered usually, it works fine, but not when rendered via the `app/views/commontator/comments/update.js.erb` file where the `CommentsController` is responsible. And the latter didn't include the `MediaHelper` yet.
> Fix editing of comments that have an annotation timestamp

- .config/.rubocop.yml
- .vscode/settings.json
- app/controllers/vignettes/info_slides_controller.rb
- app/controllers/vignettes/questionnaires_controller.rb
- app/helpers/vertices_helper.rb
- app/models/assignment.rb
- app/models/clicker.rb
- app/models/course.rb
- app/models/import.rb
- app/models/item_self_join.rb
- app/models/lecture.rb
- app/models/manuscript.rb
- app/models/medium.rb
- app/models/term.rb
- app/models/watchlist.rb
- app/models/watchlist_entry.rb
- config/initializers/shrine.rb
As usual, a new RuboCop update also comes with new cops. Here, I only addressed trivial ones. I've disabled more complex ones in `.rubocop.yml`, e.g. `Rails/InverseOf` as this would require manual testing afterwards. Those I flagged with a TODO note and we should revisit them in the future, see #794.
Off-topic: updates a CSpell VSCode configuration.
> Autocorrect or disable new RuboCop cops

- app/models/submission_invite.rb
- spec/cypress/e2e/submissions_spec.cy.js
- spec/cypress/support/timecop.js
Fixes #798 by not showing invite links on inactive assignments anymore. The button didn't work because our backend correctly handled the case and prevented joining an inactive assignment, but we shouldn't show the button in the first place. Follow-up to #785.
I've added a Cypress test such that this doesn't happen again.
> Prevent showing invites for inactive assignments

- db/interactions_schema.rb
This PR updates the interactions schema to Rails 8: it updates the ActiveRecord schema version and corrects the extension name for the interactions schema.
> Update Interactions Schema to Rails 8

- docker/development/docker-compose.yml
Follow-up to #736 where this config was changed. We had the wrong username assigned locally for our test database. @fosterfarrell9 found this out after a complete clean install of the Docker Containers.
> Fix test database username locally

- .config/commands/docker.justfile
- INSTALL.md
In alignment with https://github.com/MaMpf-HD/mampf-init-data/pull/1, where a new database seed is constructed for local development, we remove the timestamp from the `mampf.sql` filename. This makes it possible to update the seed without having to make changes here in the MaMpf repo.
> Use generic name for local database seed SQL file

- .github/dependabot.yml
This initializes our [dependabot configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates). For the moment, I've deactivated all pull requests, see also the [options reference](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference) for the [`open-pull-requests-limit`](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#open-pull-requests-limit-). Still, having configured our package ecosystems may help to get better insights on the GitHub Security tab of the MaMpf repo. PRs might still be created due to this:
> Security updates have a separate, internal limit of ten open pull …
> Init dependabot config

- app/helpers/pagy_helper.rb
This PR makes the `pagy_bootstrap_nav` method more robust. Without this PR, just go to your local development setting and open `/watchlists`. Unless you added something to the watchlist, you will get an exception because the index action of the watchlists controller renders the `show` template in this case, without setting the pagy variable. The change in this PR fixes this.
> Fix nil check in pagy_bootstrap_nav
