- app/views/shared/_footer.html.erb
Now that I got to know bootstrap a little bit better, changed the design of the footer on mobile devices.
The desktop version should stay identical
> Improved the responsiveness of the new footer

- config/locales/de.yml
> Korrekturersuch

- config/environments/docker_development.rb
Signed-off-by: Christian Heusel <christian@heusel.eu>
> add missing env setting

- INSTALL.md
Add documentation on how to use the prepopulated database for docker development.
> Docker installation

- app/helpers/application_helper.rb
- app/views/media/play.html.erb
This solves #60 at least for THymE Player.
> add medium info to page title for THymE player

- app/assets/javascripts/thyme.coffee
This pull request adds an event listener to mouse clicks in THymE video player. Clicking inside the video should toggle play.
> toggle play when clicking in video in thyme player

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/profile.scss
- app/assets/stylesheets/search.scss
This removes a side effect introduced by #59 by preventing the loading of email.scss anywhere.
> prevent email.scss from being loaded anywhere

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/email.scss
- app/helpers/email_helper.rb
- app/mailers/application_mailer.rb
- app/mailers/my_mailer.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/layouts/devise_mailer.html.erb
- app/views/main/start.html.erb
- app/views/notification_mailer/announcement_email.html.erb
- app/views/notification_mailer/new_course_email.html.erb
- app/views/notification_mailer/new_lecture_email.html.erb
- app/views/profile/show_accordion.coffee
- config/locales/de.yml
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- config/locales/en.yml
Reverts fosterfarrell9/mampf#67
> Revert "Revert "Mail design""

- config/locales/en.yml
> terminology "Sichtbarkeit"

- Gemfile
- README.md
- app/assets/javascripts/lectures.coffee
- docker/development/Dockerfile
- docker/production/Dockerfile
- docker/run_tests/Dockerfile
Bumped to Ruby 2.7.2
Closes #102
> Bump Ruby #102

- app/controllers/quiz_certificates_controller.rb
- app/controllers/tutorials_controller.rb
- app/models/ability.rb
- app/models/medium.rb
- app/models/quiz_certificate.rb
- app/models/quiz_round.rb
- app/models/user.rb
- app/views/quiz_certificates/_claim.html.erb
- app/views/quiz_certificates/_form.html.erb
- app/views/quiz_certificates/_validation_result.html.erb
- app/views/quiz_certificates/claim.coffee
- app/views/quiz_certificates/validate.coffee
- app/views/quizzes/_finale.html.erb
- app/views/quizzes/proceed.coffee
- app/views/submissions/_card_main.html.erb
- app/views/tutorials/index.html.erb
- app/views/tutorials/validate_certificate.coffee
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20201030104932_create_quiz_certificates.rb
- db/schema.rb
- spec/factories/quiz_certificates.rb
- spec/models/quiz_certificate_spec.rb
This PR implements a feature requested by a user. It allows users to get a certificate for a quiz, which is basically a code that enables you to "prove" to your tutor that you completed a certain quiz. Tutors can check validity of codes.
> establish quiz certification

- app/controllers/submissions_controller.rb
Bug fix
- Linter
Creation of submissions fails if maximum teams size is 1
> Submission creation fix

- docker/production/Dockerfile
- docker/production/entrypoint-master.sh
> Sidekiq fixes #84

- app/controllers/registrations_controller.rb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- docker/development/docker-compose.yml
> Registration limit via ENV

- app/controllers/registrations_controller.rb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- docker/development/docker-compose.yml
> Registration limit via ENV (#144)

- .erb-lint.yml
- .github/pull_request_template.md
- .github/workflows/linter.yml
- app/controllers/registrations_controller.rb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- docker/development/docker-compose.yml
Pipeline update 
There are no checks for linters
Three linters are called in parallel
> Linter actions

- config/routes.rb
> Remove redundant show action for submissions

- app/views/items/_items.html.erb
> fix an issue in #161

- .github/workflows/linter.yml
- app/uploaders/vtt_uploader.rb
> Fix broken THymE

- app/models/submission.rb
Feature
Team members for submission are sorted as Rails/PostgreSQL see fit.
Team members for submission are sorted alphabetically.
> order team members for submission alphabetically

- app/controllers/submissions_controller.rb
bug fix
Missing assignment of @assignment variable in submissions_controller#redeem_code
> fix missing assignment variable

- app/models/tutorial.rb
feature
CSV export for tutorials includes only teams that have a proper submisssion (i.e. where a file was submitted)
> csv export only for teams that have a proper submission

- app/controllers/profile_controller.rb
- app/models/lecture.rb
- app/models/user.rb
- app/models/user_favorite_lecture_join.rb
- app/views/main/start.html.erb
- app/views/main/start/_lecture_card.html.erb
- app/views/profile/star_lecture.coffee
- app/views/profile/unstar_lecture.coffee
- app/views/shared/_dropdown_favorite_lectures.html.erb
- app/views/shared/_lecture_button.html.erb
- app/views/shared/_navbar.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20201124223030_create_user_favorite_lecture_joins.rb
- db/schema.rb
- spec/factories/user_favorite_lecture_joins.rb
- spec/models/user_favorite_lecture_join_spec.rb
Feature
Users can star and unstar lectures. The starred lectures appear in a dropdown menu in the navbar, so you can directly navigate to them, saving a few clicks.
> Favorite lectures

- docker/development/Dockerfile
Bug fix
#108 
This is only relevant for development.
> Ghostscript policy for development

- INSTALL.md
- docker/development/docker-compose.yml
> Add tutorial and submission data to sample database

- app/models/lecture.rb
> Robust deletion date for submissions

- app/views/layouts/mailer.html.erb
- app/views/layouts/mailer.text.erb
- config/locales/de.yml
- config/locales/en.yml
Feature
In the mail footer there is i short info on what to do if links do not work when called directly form the mail client.
> add info about links in mail footer

- app/models/user.rb
- config/initializers/devise.rb
- db/migrate/20201206161307_add_lockable_to_devise.rb
- db/schema.rb
Features
Users can be locked and unlocked (via console user#lock_access! and user#unlock_access!)
This involves a migration, so run `db:migrate`
> Add lockable to devise

- app/views/exception_handler/mailers/new_exception.html.erb
> Add some information from the request object

- app/views/announcements/_row_for_lecture_edit.html.erb
- app/views/lectures/edit/_announcements.html.erb
> Fix announcement partial mixup

- app/controllers/announcements_controller.rb
- app/controllers/lectures_controller.rb
- app/controllers/media_controller.rb
- app/mailers/notification_mailer.rb
Feature
Some mails are still sent synchronous.
All mails are sent asynchronous.
> make all mail deliveries asynchronous

- .browserslistrc
- .gitignore
- Gemfile
- Gemfile.lock
- app/javascript/packs/application.js
- app/javascript/packs/application.sass
- app/javascript/packs/hello_coffee.coffee
- app/views/assignments/_form.coffee.erb
- app/views/assignments/_form.html.erb
- app/views/assignments/edit.coffee
- app/views/assignments/new.coffee
- app/views/layouts/_head.html.erb
- babel.config.js
- bin/webpack
- bin/webpack-dev-server
- config/webpack/development.js
- config/webpack/environment.js
- config/webpack/loaders/coffee.js
- config/webpack/loaders/css.js
- config/webpack/loaders/scss.js
- config/webpack/production.js
- config/webpack/test.js
- config/webpacker.yml
- docker/development/Dockerfile
- docker/development/docker-compose.yml
- docker/production/Dockerfile
- package.json
- postcss.config.js
- yarn.lock
> Datepicker to coffee

- .github/workflows/linter.yml
- .github/workflows/test-integration.yml
- config/webpacker.yml
- docker/run_cypress_tests/Dockerfile
- docker/run_cypress_tests/docker-compose.local.yml
- docker/run_cypress_tests/docker-compose.yml
Upgrade dependencies in linter tests & get cypress working with webpacker
> Upgrade linter

- app/models/course.rb
- app/models/item.rb
- app/models/lecture.rb
- app/models/section.rb
- app/uploaders/video_uploader.rb
- spec/factories/chapters.rb
- spec/factories/courses.rb
- spec/factories/media.rb
- spec/factories/notions.rb
- spec/factories/tags.rb
- spec/models/course_spec.rb
- spec/rails_helper.rb
- spec/support/database_cleaner.rb
Unit tests for the Course model 
For `rspec`, `config.use_transactional`_fixtures has been set to `false` to allow database_cleaner to do its'  job. `database_cleaner` is configured in `spec/support/database_cleaner.rb`. This has been done as `rspec` did not roll back inside `before :all` blocks, resulting in problems with validations with uniqueness checks.
Also, some factories have …
> Unit tests for courses

- app/models/course.rb
- app/models/lecture.rb
- app/models/medium.rb
- app/models/question_sampler.rb
- app/models/teachable_parser.rb
- app/models/user.rb
- app/views/profile/_details.html.erb
- spec/factories/question_samplers.rb
- spec/factories/teachable_parsers.rb
- spec/models/course_spec.rb
- spec/models/question_sampler_spec.rb
- spec/models/teachable_parser_spec.rb
The `Course` model has been refactored. In the process several methods have been extracted to new service PORO models `QuestionSampler` and `TeachableParser`.
> Refactor course

- app/assets/javascripts/upload.coffee
- app/views/submissions/_form.html.erb
> Fixes #117

- app/views/tutorials/_submission_row.html.erb
- config/locales/de.yml
- config/locales/en.yml
Feature
Add copy button to tutorial overview
No
> Add Copy of Mail Adresses

- app/controllers/lectures_controller.rb
- app/controllers/profile_controller.rb
- app/models/ability.rb
- app/views/lectures/show.html.erb
- app/views/lectures/subscribe_page.html.erb
- config/locales/de.yml
- config/locales/en.yml
- config/routes.rb
- spec/cypress/integration/courses_spec.js
Feature
#197 
You can try to subscribe on to a lecture on its page.
No.
> Subscribe lecture button fixes #197

- INSTALL.md
- app/controllers/registrations_controller.rb
- app/javascript/packs/application.js
- app/views/devise/registrations/new.html.erb
- config/locales/devise.de.yml
- config/locales/devise.en.yml
- package.json
- yarn.lock
Feature
No captcha is used
A captcha is required to signup.
Yes. Please set the new enviroment variables accordingly.
> Captcha2go

- .github/workflows/test-integration.yml
- app/controllers/lectures_controller.rb
- app/models/ability.rb
- spec/cypress/app_commands/scenarios/teacher.rb
- spec/cypress/integration/courses_spec.js
Bug fix
- [x ] E2E Tests for the changes have been added  via Cypress
It was impossible to subscribe if you were a teacher or editor. Furthermore, The blocking of users in case of unpublished lectures was insufficient.
Fixed both issues.
> Fix lecture button and testing

- app/controllers/lectures_controller.rb
> fixes #233

- app/assets/javascripts/upload.coffee
- app/uploaders/correction_uploader.rb
- app/uploaders/submission_uploader.rb
Increase Upload Limit for Submissions and Corrections.
> Increase upload limit

- .github/workflows/test-integration.yml
- docker/development/Dockerfile
- docker/development/docker-compose.yml
- docker/run_cypress_tests/Dockerfile
- docker/run_cypress_tests/Dockerfile_cypress
- docker/run_cypress_tests/docker-compose.local.yml
- docker/run_cypress_tests/docker-compose.yml
- docker/run_cypress_tests/run_tests.sh
- entrypoint.sh
- initialize.sh
This bug is an enhancement and clears up some code in the entrypoint / docker files :blush:
* The webpacker container runs the regular entrypoint ➡️ exceptions are thrown during boot!
* every line in `entrypoint.sh` has the same pipe
* environment variables for the tests are set
* The webpacker container does not try to execute the db migrations
* the init functionality in `entrypoint.sh` is put in an extra file and the output piped once
* the testcontainer has no external dependency (i.e. on `yarn install`)
* …
> Improve docker startup sequence

- config/initializers/spec_files.rb
- spec/factories/courses.rb
- spec/factories/media.rb
- spec/factories/submissions.rb
- spec/factories/vtt_containers.rb
Change way fixture files are referenced.
> Introduce specfiles var for files in spec

- Gemfile.lock
- docker/development/Dockerfile
- docker/production/Dockerfile
- docker/run_cypress_tests/Dockerfile
- docker/run_tests/Dockerfile
Fixes broken dependency of rails and installs shared-mime-info
Installing shared-mime-info is needed to run this.
> Install shared-mime-info and upgrade mimemagic

- app/workers/submissions_cleaner.rb
> fixes #259

- README.md
> Merge mampf_next into main

- app/models/submission_cleaner.rb
- config/locales/de.yml
> send submission deletion info mails in batches

- README.md
> Merge mampf-next into main

- config/locales/en.yml
> apply patch by hungrywords

- docker/production/Dockerfile
Bug fix
sidekiq assets are not copied (wrong version)
sidekiq assets are copied
> update sidekiq version

- docker/development/Dockerfile
- docker/production/Dockerfile
This PR increases the robustness of the production dockerfile as requested by @fosterfarrell9 😄 
The sidekiq assets are copied from a fixed path determined by the version
The sidekiq assets are copied from the currently installed version
hopefully not!
> re-structure and clean up dockerfile

- app/javascript/packs/application.js
- app/views/devise/registrations/new.html.erb
- package.json
- yarn.lock
Localizes the captcha in registration process.
> Set data lang & upgrade friendly-challenge

- config/initializers/commontator.rb
> comment order changed to l

- app/views/layouts/geogebra.html.erb
> Fixed missing script tag in  geogebra.html.erb

- app/models/user.rb
- app/views/administration/index/_my_lectures.html.erb
- config/locales/de.yml
- config/locales/en.yml
> Synced translation files, Fixes #297

- app/views/layouts/_head.html.erb
> Highresicon ,fixes #308

- Gemfile
- Gemfile.lock
- MONITORING.md
- config/initializers/prometheus_exporter.rb
- docker/development/prometheus.yml
- docker/production/entrypoint-master.sh
- docker/production/proxy_server_config.txt
- lib/collectors/mampf_collector.rb
adds prometheus exporter to provide monitoring.
> monitoring fixes #306

- INSTALL.md
- app/models/medium.rb
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)*
Introduces the possibility to display correct filenames, when pressing the display button.
Files have a cryptic filename, when viewed in browser.
The rewrite in the media server allows correct filenames to be passed.
No. Switching on of this feature is explicitly required.
> Advanced rewrite: Filenames

- app/controllers/media_controller.rb
- app/models/medium.rb
- app/views/media/_manuscript_card.html.erb
- app/views/media/_medium.html.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20210610230901_add_file_last_edited.rb
- db/schema.rb
Added an indicator for updated exercise sheets. In the overview, it manifests as the card subheader turning red. If you click on an updated exercise sheet, you see when it got updated.
Compares the "released_at" and "updated_at" Medium variables to see if the sheet got updated.
> Updated sheets

- .github/workflows/linter.yml
- .github/workflows/test-integration.yml
- docker/run_cypress_tests/Dockerfile
- docker/run_cypress_tests/Dockerfile_cypress
- docker/run_cypress_tests/docker-compose.local.yml
- spec/cypress/integration/media_spec.js
- spec/cypress/integration/thredded_spec.js
- spec/factories/media.rb
- yarn.lock
> Adding new tests, updating docker to use node 14

- app/controllers/submissions_controller.rb
- app/models/submission.rb
- app/models/tutorial.rb
Adds the ability to upload different fileformats then the submission as correction.
> Return more fileformats

- Gemfile.lock
- app/assets/javascripts/courses.coffee
- app/assets/javascripts/upload.coffee
- app/controllers/users_controller.rb
- app/models/user.rb
- app/uploaders/profileimage_uploader.rb
- app/views/users/_basics.html.erb
- app/views/users/_upload_image.html.erb
- app/views/users/teacher.html.erb
- config/routes.rb
- db/migrate/20210629133704_add_profile_image_to_user.rb
- db/schema.rb
- spec/cypress/integration/admin_spec.js
- spec/cypress/integration/courses_spec.js
- spec/cypress/support/yarn.lock
This PR introduces profile images for teachers.
You need to run db:migrate
> First draft of profile image implementation

- app/views/layouts/edit_clicker.html.erb
Bug fix
The `edit_clicker.html.erb` layout file has a syntax error which prevents Rails' javascript assets being loaded, which in turn results in a non-functional page.
Syntax error has been fixed, page is working.
> fix broken clicker layout

- app/views/tutorials/_submission_row.html.erb
fixed the nil error for when a late submission gets accepted
> Fix late assignment accept error

- app/controllers/assignments_controller.rb
- app/models/submission_cleaner.rb
- app/models/term.rb
- app/views/assignments/_form.html.erb
- app/views/assignments/_row.html.erb
- app/views/lectures/edit/_assignments.html.erb
- app/views/submissions/_card_main.html.erb
- config/locales/de.yml
- config/locales/en.yml
- db/migrate/20210923085744_add_protected_to_assignment.rb
- db/schema.rb
Allows the protection of homework. This homework will be stored indefinitely.
All Homework is deleted on a fixed date after the semester.
Some Assignments can be protected.
> Protected homework

- app/models/ability.rb
Bug fix.
Video TOCing broken due to typo in `ability.rb`
Bug fixed.
> fix video tocing

- app/assets/javascripts/media.coffee
bugfix
In seminars, video upload fails for generic users.
Bug is fxed.
> fix broken video upload for seminars

- .github/workflows/codecov.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
As it will be deprecated
Bug fix
> Upgrade codecov-action to v2

- app/models/watchlist.rb
- docker/run_tests/docker-compose.yml
- spec/factories/watchlist_entries.rb
- spec/models/watchlist_entry_spec.rb
- spec/models/watchlist_spec.rb
Rspec tests for Watchlist and WatchlistEntry
> Watchlist rspec

- Gemfile
- app/validators/http_url_validator.rb
- app/views/quizzes/_finale.html.erb
- app/views/quizzes/proceed.coffee
- docker/development/docker-compose.yml
- spec/cypress/app_commands/scenarios/editor.rb
- spec/cypress/integration/media_spec.js
Fixes the errors introduced in the update of ruby from 2.7 to 3.0.
Removes XKCD gem for now.
> Updatetests and errorfixes

- config/routes.rb
> handled post put patch delete routing for root

- app/abilities/vertex_ability.rb
- app/abilities/watchlist_entry_ability.rb
> small fixes to two ability files

- SECURITY.md
Introduction of a security policy (see #356)
> set up security policy

- app/abilities/medium_ability.rb
- app/models/medium.rb
Bug fixes
Accessing quiz questions pages for generic users had been disabled, so no quizzes can be taken.
Previous behavior is restored.
> Fix regressions introduced by refactor_abilities

- spec/cypress/integration/media_spec.js
- spec/cypress/integration/submissions_spec.js
- spec/cypress/integration/thredded_spec.js
- spec/factories/lectures.rb
> added two more tests

- app/assets/javascripts/media.coffee
- app/models/subject.rb
- app/models/talk.rb
- app/views/administration/classification.html.erb
Several bug fixes for upcoming v1.4 release
> Preparev14

- app/models/xkcd.rb
- app/views/quizzes/_finale.html.erb
- app/views/quizzes/proceed.coffee
- config/locales/de.yml
- config/locales/en.yml
> added xkcd back without gem dependency

- app/abilities/submission_ability.rb
- app/controllers/submissions_controller.rb
- app/models/submission.rb
- app/views/courses/search/_form.html.erb
- app/views/lectures/_new.html.erb
- app/views/main/start/_lecture_search.html.erb
- app/views/media/catalog/_search_form.html.erb
- app/views/submissions/_card_main.html.erb
All the fixes for for the 1.4.1 update.
> V1.4.1 fixes

- app/views/answers/_card.html.erb
> fix missing partial bug by removing incorrect file extension

- app/controllers/quizzes_controller.rb
> fix issue 397

- app/models/item.rb
- app/models/manuscript.rb
- app/views/media/_content.html.erb
- config/locales/de.yml
- config/locales/en.yml
Fixes #399 
Issue #399 
Issue #399 is fixed.
> fix issue 399

- INSTALL.md
> Install.md updated

- config/routes.rb
> fix issue 403

- app/mailers/notification_mailer.rb
- app/models/submission_cleaner.rb
- app/models/term.rb
- app/views/notification_mailer/submission_deletion_email.html.erb
- app/views/notification_mailer/submission_deletion_lecture_email.html.erb
- app/views/notification_mailer/submission_destruction_email.html.erb
- app/views/notification_mailer/submission_destruction_lecture_email.html.erb
- config/locales/de.yml
- config/locales/en.yml
- spec/models/submission_cleaner_spec.rb
> Fix submision cleaner

- app/assets/javascripts/_selectize_turbolinks_fix.js
- app/views/courses/_new.html.erb
- app/views/courses/_tags.html.erb
- app/views/erdbeere/_find_tags.html.erb
- app/views/lectures/_new.html.erb
- app/views/lectures/edit/_people.html.erb
- app/views/lectures/show_random_quizzes.html.erb
- app/views/lessons/_basics.html.erb
- app/views/media/_basics.html.erb
- app/views/media/catalog/_search_form.html.erb
- app/views/media/catalog/_tags_form.html.erb
- app/views/sections/_basics.html.erb
- app/views/tags/_basics.html.erb
- app/views/tags/_select_related_tags.html.erb
- app/views/talks/_assemble_form.html.erb
- app/views/talks/_basics.html.erb
- app/views/talks/_new.html.erb
- app/views/tutorials/_form.html.erb
- app/views/users/_generic_users.html.erb
Adds localization for search TomSelect message about search without results
> add localization for no-result query information in tomselect

- app/views/exception_handler/mailers/new_exception.html.erb
> sensitive parameter filtering for exception mails

- app/assets/javascripts/_selectize_turbolinks_fix.js
> Set maximum dropdown options for TomSelect to unlimited

- app/assets/javascripts/questions.coffee
> add missing evaluation

- app/assets/javascripts/questions.coffee
> prevent erraneous paramater evaluation

- config/initializers/assets.rb
In my local setup, there was a segfault in the run_cypress_tests docker conatiner related to a concurrency issue.
The PR fixes this. 
> fix concurrency issue in testing

- .github/PULL_REQUEST_TEMPLATE/feature.md
- .github/pull_request_template.md
* **What kind of change does this PR introduce?** 
Bug fix / docs update
* **What is the current behavior?**
The PR templates checkboxes are unalinged with the questions they belong to
The PR templates are a little bit more consistent
I dont think so :D
None
> correct the alignment in the PR templates

- .github/workflows/linter.yml
* **What kind of change does this PR introduce?**
Bug fix for Issue #435
Linter run fails
Linter run works
No
🚫
> Linter CI fix

- app/assets/stylesheets/landing.scss
- app/views/devise/sessions/new.html.erb
- app/views/layouts/devise.html.erb
- config/locales/de.yml
- config/locales/devise.de.yml
- config/locales/en.yml
Some small improvements for the landing page, e.g. "Du" instead of "du" consistently, other wording changes and very small layout changes.
> Improve landing page (small changes)

- app/views/shared/_sidebar.html.erb
We need to pass in a parameter to path methods, here: `lecture_path(...)`. We also check if this variable is present at all.
> Hotfix for searchbar

- app/controllers/main_controller.rb
- config/routes.rb
This PR adds authentification to route sin the main controller, fixing an issues caused by the new navbar.
Also, the old home path is removed, so users who had bookmarked this will be redirected.
> add authentification to main routes and remove old home

- app/controllers/users_controller.rb
Add authorization to generic user list
> [Security fix] Add authorization to generic user list API

- docker/production/docker-compose.production.yml
- **What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Switch deployment: now from main branch, so that we get rid of the production branch.
> Deploy from main branch (not production branch)

- Gemfile.lock
Updates for sidekiq, nokogiri and rack.
> update some gems for security

- app/controllers/users_controller.rb
- app/views/users/_basics.html.erb
- config/routes.rb
We refactor the user_controller and make a change to the admin user interface requested by one admin.
> refactor controller

- app/abilities/user_ability.rb
- app/controllers/users_controller.rb
- app/views/users/_basics.html.erb
This restricts PR what part of the user profile admins can edit.
> restrict user editing

- app/abilities/user_ability.rb
- app/controllers/users_controller.rb
- app/views/users/_basics.html.erb
- config/routes.rb
This brings #487 to production.
> Bring #487 to production

- app/helpers/media_helper.rb
Fixes a bug  that is triggered by external link descriptions that are nil
> Hotfix: correct check for external reference description

- app/assets/stylesheets/navbar.scss
> Fix color for comment previews

- app/views/media/fill_quizzable_preview.coffee
> Fix flickering for quiz previews

- app/controllers/users_controller.rb
- app/views/users/_generic_users.html.erb
- app/views/users/_modal.html.erb
- app/views/users/index.html.erb
- app/views/users/list.json.jbuilder
This PR just cleans up the user controller and views a little, getting rid of a variable that is no longer needed because data are now retrieved via ajax. Because of the many possible changes via #476, this is not a thorough refactorization, only some obvious stuff is changed.
> Refactor user controller and views

- app/assets/stylesheets/comments.scss
- app/views/commontator/comments/_form.html.erb
- app/views/commontator/comments/new.js.erb
- app/views/media/_destination_cards.html.erb
> Patch release 1.7.1

- app/javascript/packs/application.js
- app/views/layouts/_head.html.erb
- app/views/lectures/edit/_content.html.erb
- app/views/lectures/edit/_seminar_content.html.erb
- app/views/lectures/show/_content.html.erb
- app/views/lectures/show/_structures.html.erb
> Fix masonry grid not properly rendered on page load

- app/views/tutorials/bulk_upload.coffee
> Bring hotfix (release 1.8.1) back to dev

- app/assets/javascripts/upload.coffee
- app/uploaders/correction_uploader.rb
- app/uploaders/submission_uploader.rb
- app/views/submissions/_correction_upload.html.erb
- app/views/tutorials/_bulk_correction_form.html.erb
- app/views/tutorials/_submission_row.html.erb
- app/views/tutorials/bulk_upload.coffee
- config/locales/de.yml
- config/locales/en.yml
- #551
- #552
---
- #533 
- #527 - add `ENV` variable to production ⚠
- #543
> Continuous Release 1.8.2

- app/models/quiz_certificate.rb
> Fix inverse_of quiz certificate

- app/controllers/commontator/comments_controller.rb
- app/controllers/main_controller.rb
- app/controllers/readers_controller.rb
- app/models/user.rb
- app/views/main/comments.html.erb
Fixes #573.
<sub>Previous PR for this was #576, closed in favor of this one as this directly branches off the new "dev" branch.</sub>
> Fix comment status

- db/migrate/20240116180000_fix_unread_comments_inconsistencies.rb
See the added code comment for an explanation of this PR
> Don't raise exception for broken migration anymore

- app/assets/javascripts/lectures.coffee
> Fix broken tag highlighting for lectures admin view

- config/locales/en.yml
This adds a missing key in the english locale file.
> Hotfix: Add missing key in locale file

- .config/eslint.mjs
- package.json
- yarn.lock
Upgrade Node.js dev dependencies & in particular ESLint.
**Run `yarn install` locally to have up-to-date dependencies.**
> Upgrade Node.js dev dependencies & fix ESLint config

- app/controllers/lectures_controller.rb
- app/views/lectures/edit/_comments.html.erb
> Add UI feedback for closing/opening discussions

- app/assets/javascripts/vignettes/codename_validations.js.erb
- app/assets/javascripts/vignettes/edit.js.erb
- app/models/vignettes/csv_handler.rb
This fixes some small mistakes related to the new vignettes #737
> Fix small Vignettes mistakes

- docker/development/docker-compose.yml
- docker/test/docker-compose.yml
See also [EOL](https://endoflife.date/postgresql).
> Update PostgreSQL 15->17

- app/controllers/lessons_controller.rb
- app/controllers/media_controller.rb
- app/controllers/submissions_controller.rb
- app/helpers/talks_helper.rb
- app/models/question.rb
- app/models/tag.rb
- app/models/user.rb
- app/workers/user_cleaner_job.rb
New linting errors appeared after #804, this PR fixes them. Note that [`Style/CollectionQuerying`](https://docs.rubocop.org/rubocop/cops_style.html#stylecollectionquerying) is unsafe.
> Fix RuboCop lint errors

- docker/development/Dockerfile
Follow-up to #783. Fixes #813. Apparently, I forgot to update the client version as well, which is what we catch up on in this PR.
> Upgrade PostgreSQL client to 17 in development

- .github/dependabot.yml
Fix as direct follow-up to #817.
> Fix dependabot config array syntax
